jwt:
  secret: cp06FBsY4rqArnpuGPdY8jq3RFhFHX7AIpjEYLyHyFDXHJNIgAih7rD4kuXABevtF2SN5Vy8Sz012ew1dewdcsac213SUPERSEGURACLAVEJWT2025ULTRALARGAPARAH512sdaddasdsadsadasd
  expiration-ms: 3600000   # 1 hora
  refresh-expiration-ms: 86400000 # 24 horas

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false