server:
  port: 8051

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/auth_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: "initial setup"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

jwt:
  secret: cp06FBsY4rqArnpuGPdY8jq3RFhFHX7AIpjEYLyHyFDXHJNIgAih7rD4kuXABevtF2SN5Vy8Sz012ew1dewdcsac213SUPERSEGURACLAVEJWT2025ULTRALARGAPARAH512sdaddasdsadsadasd
  expiration-ms: 3600000   # 1 hora
  refresh-expiration-ms: 86400000 # 24 horas